services:
    marttiphpbb.extrastyle.event.listener:
        class: marttiphpbb\extrastyle\event\listener
        tags:
            - { name: event.listener }

    marttiphpbb.extrastyle.service.store:
        class: marttiphpbb\extrastyle\service\store
        arguments:
            - '@config_text'
            - '@cache.driver' 
       
    marttiphpbb.extrastyle.controller:
        class: marttiphpbb\extrastyle\controller\main
        arguments:
            - '@marttiphpbb.extrastyle.service.store'

