services:
    marttiphpbb.extrastyle.event.listener:
        class: marttiphpbb\extrastyle\event\listener
        tags:
            - { name: event.listener }

    marttiphpbb.extrastyle.event.mcp_forum_listener:
        class: marttiphpbb\extrastyle\event\mcp_forum_listener
        arguments:
            - '@dbal.conn'
            - '%tables.topics%'
            - '%tables.forums%'
            - '@config'
            - '@auth'
            - '@language'
            - '@request'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@log'
            - '@user'
        tags:
            - { name: event.listener }
    marttiphpbb.extrastyle.service.store:
        class: marttiphpbb\extrastyle\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'        
